### ISSUE TITLE
Add CI task to check if the generated API is outdated

### ISSUE THREAD

**Issue by tkilias** [exasol/saas-api-python#8]
- The published json description for the API can change without our knowledge
- For that reason, the generated API can get outdated and we need to check if it is up-to-date 
- In the CI we need to run the generation and compare with git status or git diff if we have to update
- This job has to run daily and maybe send a slack message

**Comment by ckunki** [comment]
I ran an [experimental build](https://github.com/exasol/saas-api-python/actions/runs/8751727261/job/24017942170) and verified the message has been published to our company chat system:

![image](https://github.com/exasol/saas-api-python/assets/81821845/e266f6bd-f87c-4afc-a240-c6ff28fc45f2)
